mongodb-js/zstd

.github/pull_request_template.md

chore: add PR description template

---

.cargo/config.toml
.github/workflows/CI.yml
README.md
index.js
npm/linux-arm64-musl/README.md
npm/linux-arm64-musl/package.json
npm/linux-x64-musl/README.md
npm/linux-x64-musl/package.json
package.json

Add `linux-x64-musl` and `linux-arm64-musl` builds to support Alpine Linux Docker images
https://jira.mongodb.org/browse/NODE-4569
**Note:** "musl" builds related changes in GitHub Actions workflows were copied from a clean NAPI-RS project created by `@napi-rs/cli@2.12.1` with "yarn" commands replaced with corresponding "npm" ones

feat(NODE-4569): add "musl" builds for Alpine Linux

---

Cargo.toml

Update to zstd-sys to get zstd 1.5.5 security fix.
Updates underlying dependency on zstd-sys.
None
NODE-5177

fix(NODE-5177): update to latest zstd-sys

---

package-lock.json
package.json

Update the following dev dependencies
* "@napi-rs/cli": "^2.16.2"

chore(NODE-5450): update zstd dependencies

---

README.md

NODE-5528
Added table with version compat info for the nodejs driver
This is documentation
Clarity about add-on compatibility
- [N/A] Changes are covered by tests
- [N/A] New TODOs have a related JIRA ticket

docs(NODE-5528): add driver version compat table

---

package-lock.json
package.json

Update dev and prod dependencies for mongodb-js/zstd
Updating ` chai  ^4.3.10  →  ^5.1.0 ` causes error, so only updated the following:
```
@napi-rs/cli  ^2.16.5  →  ^2.18.0
mocha         ^10.2.0  →  ^10.3.0
prettier       ^2.8.8  →   ^3.2.5
```
No.
Keep dependencies up to date.

chore(NODE-5833): Update Zstd dependencies

---

.github/dependabot.yml
package-lock.json
package.json

Updates development dependencies and adds a Rust/npm dependabot config.

chore(NODE-6272): update dev dependencies and add dependabot config

---

.github/workflows/CI.yml

Fixes native build for darwin-x86_64
- Updates the npm build steps in CI fr x86_64 to specifically target that platform.
- Updates download artifact actions to latest v4, since v2 was removed.
None
Broken installs for 1.2.1 on darwin x86_64

fix(NODE-6381): use targeting for x86_64 darwin

---

.github/dependabot.yml

Adds dependabot config to update Github Actions.
Adds dependabot config to update Github Actions.
None
NODE-6569

chore(NODE-6569): add dependabot for github actions

---

.github/docker/Dockerfile.glibc
.github/docker/Dockerfile.musl
.github/workflows/test.yml
.gitignore
.mocharc.json
addon/compression.h
binding.gyp
etc/docker.sh
etc/install-zstd.sh
package-lock.json
package.json
test/index.test.js

Expands the testing matrix to all supported platforms, architectures and node versions. 
As mentioned today at standup, Node18+ alpine arm64 builds are skipped.  They will be addressed in https://jira.mongodb.org/browse/NODE-6575.

ci(NODE-6570): Test on all supported platforms and Node versions

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md

A passing SSDLC release run is available here: https://github.com/mongodb-js/zstd/actions/runs/12056025639
Note that we can't actually confirm everything looks right until we do an actual release and can inspect the contents of the SSDLC report in s3.  Once this PR merges, I can run the beta release and we can confirm.

feat(NODE-6588): add ssdlc to zstd

---

test/index.test.js

A new regression test has been added to ensure that compressionLevel is respected by our C++ bindings.

test(NODE-6586): add regression test to ensure compressionLevel works

---

.github/workflows/test.yml
binding.gyp
etc/install-zstd.sh

Set errexit in install-zstd.sh.
This causes the install script to fail on windows because the tarball contains symlinks, which cannot be extracted.  The symlink files are not source files, so the build worked without issues before this, but now that errexit is set, we cannot download and extract the zstd source code.
Instead, on windows we now download the prebuilt static library (which does not contain symlinks).

chore(NODE-6603): set errexit in install script and download prebuilt windows zstd

---

README.md

Updates the compatibility table for zstd@2.0.

docs(NODE-6595): update compatability table for zstd@2.0

---

.github/workflows/test.yml
binding.gyp
etc/install-zstd.sh

This PR reverts https://github.com/mongodb-js/zstd/pull/51 and goes back to compiling on Windows.  

build(NODE-6604): fix windows builds

---

README.md

docs: update prebuild matrix in readme

---

.github/workflows/test.yml
binding.gyp
etc/install-zstd.sh

fix: bundle release build on windows

---

.github/workflows/release.yml
release-please-config.json

- remove alpha tag from npm publish
- config release-please to publish to GH latest

chore: prepare for non-alpha release

---

README.md

docs(NODE-6573): add 1.x deprecation note to readme

---

.github/docker/Dockerfile.musl

We don't need vim on every install of our alpine package, only when we're debugging inside the container

chore: remove vim from musl docker file build
